### PR TITLE
added missing react-nouislider to package.json

### PR DESCRIPTION
**Pull request by kmkanagaraj**

### CODE REVIEW

**Comment by kmkanagaraj** [comment]
I am not sure if react-uislider is actually used. I don't see any references of it except an import in main.less

**Comment by harshavardhana** [comment]
ping @rushenn

**Comment by rushenn** [comment]
It seems like I have forgot to remove the nouislider reference completely. There is no need for nouislider as we using custom spinners for sharing. I will update the less imports.

**Comment by kmkanagaraj** [comment]
Sent another PR to remove the less import , closing this.

**Pull request closed without merging**
