### PR TITLE
Object list: Make the entire div clickable

### PR DESCRIPTION
**Pull request by siddharthkp**
Even though the entire row has a hover state, only the name is clickable.

screen shot 2016-11-14 at 5 36 52 pm

Made the entire name div clickable: 

screen shot 2016-11-14 at 5 33 51 pm

(positive) Side effect: 

screen shot 2016-11-14 at 5 34 12 pm

The name now has a blue color on hover.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Ping @rushenn can you review this ?

**Comment by rushenn** [comment]
@harshavardhana Done. It's good to go.

**Comment by rushenn** [comment]
@siddharthkp: 
at line no. 45, can you please use a <div> tag instead of <a> in order to keep the elements identical?

**Comment by siddharthkp** [comment]
@rushenn Can, but that will lead to some unnecessary css added to the anchor tag. What do you think?

**Comment by rushenn** [comment]
> unnecessary css added to the **anchor tag**

Not getting your point. Anchor tag will be replaced with the `div`and we can keep the default styling as what we have right now.

**Comment by rushenn** [comment]
@siddharthkp We can also give an extra styling `cursor: pointer `to mimic it like a link

**Comment by siddharthkp** [comment]
@rushenn The actual clickable area is what bugged me in the first place. Even if you want to keep the div, should make the anchor tag 100% size of it's parent. You don't have to mimic/workaround the functionality of the anchor tag.

**Comment by rushenn** [comment]
@siddharthkp There won't be any anchor tags as we are adding the `onClick` directly in the div. We are also working on including checkboxes for each rows and which will change the row markup entirely. Let's proceed with the div for now.

**Comment by siddharthkp** [comment]
@rushenn 
> There won't be any anchor tags as we are adding the onClick directly on the div. 
Err, I'm sorry but that doesn't sound like a good idea. I'm curious as to why would you want to use `onClick` on a div over an anchor tag. There is something that I'm missing here.

**Comment by rushenn** [comment]
@siddharthkp 

`onClick` can be used with any elements, it's not limited only for anchor tags. There is nothing wrong using an anchor tag here. You can see other column elements are currently using div tags. In order to keep the particular code base clean and identical to each other (columns), It's better to use a div here. Again, it's all for inner beauty.

**Comment by siddharthkp** [comment]
@rushenn This is becoming a purist conversation 😄 Not very productive.

I guess I'll close this PR, it's trying to do something different.

+

> We are also working on including checkboxes for each rows and which will change the row markup entirely.
For implementing this, you will have to change the way the anchor tag is placed right now.

✌️

**Pull request closed without merging**
