### PR TITLE
[WIP] Gray out access/secret fields when credentials provided in the minio env

### PR DESCRIPTION
**Pull request by vadmeste**

### CODE REVIEW

**Comment by vadmeste** [comment]
Need Rushen feedback, Could be ready today 4 august

**Comment by harshavardhana** [comment]
@rushenn ping

**Comment by krishnasrinivas** [comment]
this still has problems, will be fixed by rushan with following fix:
```
let InputGroup = ({label, id, name, value, onChange, type, spellCheck, required, readonly, autoComplete, align, className}) => {
    var input = <input id={id} name={name} value={value} onChange={onChange} className="ig-text" type={type} spellCheck={spellCheck} required={required} autoComplete={autoComplete} />
    if (readonly) input = <input id={id} name={name} value={value} onChange={onChange} className="ig-text" type={type} spellCheck={spellCheck} required={required} autoComplete={autoComplete} disabled />
    return <div className={"input-group " + align + ' ' + className}>
    {input}
        <i className="ig-helpers"></i>
        <label className="ig-label">{label}</label>
    </div>
}
```

**Comment by vadmeste** [comment]
we also need to disable two buttons in the same dialog (regenerate and set authentication).. Probably this css property could help : `pointer-events:none;`

**Comment by krishnasrinivas** [comment]
> we also need to disable two buttons in the same dialog (regenerate and set authentication).. Probably this css property could help : pointer-events:none;

fixed in the latest code PR by hiding those buttons

**Pull request merged**
